#!application-prod.yml 生产环境配置文件
server:
  port: 80 #端口
debug: false #调试模式
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false #显示sql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #驱动类
    url: jdbc:mysql://localhost:3306/hrms?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&serverTimezone=UTC
    username: root #数据库用户名
    password: lj940305 #密码
  thymeleaf:
    cache: true #缓存
    mode: HTML
  mvc:
    favicon:
      enabled: false
  output:
    ansi:
      enabled: detect #控制台多彩输出
logging:
  level: warn
  level.top: warn
  file: C:/Users/Ning/Desktop/upload/log.log